
title: Stock Reports
description: >- # This means to ignore newlines until "baseurl:"
  Equity Analysis and Trading Insights
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrmolsen.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Theme settings
remote_theme: pages-themes/hacker@v0.2.0 # Specifies the GitHub Pages remote theme to use.
plugins:
  - jekyll-remote-theme
  - jekyll-feed 
  - jekyll-seo-tag

# Build settings
markdown: kramdown # Markdown processor (kramdown is GitHub Pages default).
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false # Prevents Kramdown from forcing hard line breaks
  syntax_highlighter: rouge # Code syntax highlighter.

# Exclude from processing.
# The following items will not be processed, by Jekyll.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .nojekyll # Remove this if you add this file. You should remove it if you intend to use Jekyll.
  - README.md
  - LICENSE.md
  - .git/ # Exclude the Git directory

# You can add custom variables here that you can access in your Liquid templates
# For example, if you want to display an author name everywhere:
author:
  name: null
  email: null@n0wh3r3.com


# Uncomment this section if you want to enable a comment system (e.g., Disqus)
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "your-disqus-shortname"

# Analytics (uncomment and replace with your tracking ID)
# google_analytics: "UA-XXXXXXXXX-X"
